### ISSUE TITLE
QT-Py-ESP32-S2

### ISSUE THREAD

**Issue by igotab** [adafruit/Adafruit-QT-Py-ESP32-S2-PCB#1]
Your QT-Py-ESP32-S2 pinout shows TXD on GPIO5 (ESP32-S2 pin 10) and RXD on GPIO16 (ESP32-S2 pin 22).
These are not the hardware UART pins of ESP32-S2. 

Can you please shed some light on this.

**Comment by igotab** [comment]
Me again,
I traced the pins on your PCB fab. RXD is connected to GPIO44 (not to GPIO16) that is indeed a UART RXD pin
but TXD is connected to GPIO5 that is not a TXD pin.

**Comment by ladyada** [comment]
the s2 can mux uart to any pins, we use native usb not hardware uart
